### ISSUE TITLE
Obsidian-pieces causing problem with obsidian community Calendar plugin

### ISSUE THREAD

**Issue by prashantnag** [pieces-app/obsidian-pieces#9] opened 2023-07-17 09:18 UTC
Before Enabling the Obsidian-pieces Obsidian Side penal:
<img width="346" alt="Screenshot 2023-07-17 144449" src="https://github.com/pieces-app/obsidian-pieces/assets/15131819/00f0dffa-c6b6-4bfc-8892-b801b3f1c673">

 After Enabling the Obsidian-pieces plugin the [Calendar Plugin ](https://github.com/liamcain/obsidian-calendar-plugin) not behaving properly:

<img width="337" alt="Screenshot 2023-07-17 144528" src="https://github.com/pieces-app/obsidian-pieces/assets/15131819/40a0cc45-6ade-43a6-9bae-ad800c04d9ff">

**Comment by mason-at-pieces** [comment] 2023-07-19 18:42
Hey @prashantnag93, thanks for bringing this issue to our attention!

I would assume it is because we have overlapping CSS classes. I am going to test this out myself and see what the issue might be.

Will try to get this fixed and release this week in a patch release!

**Comment by mason-at-pieces** [comment] 2023-07-19 18:48
So I've confirmed that the CSS class name is causing the issue since the Calendar plugin uses the same name for a class we have. We will start working on prefixing our CSS classes so there isn't any overlap with other plugins.

**Comment by caleb-at-pieces** [comment] 2023-09-23 15:42
Closing, this was fixed a few weeks ago

**Closed as completed by caleb-at-pieces** 2023-09-23 15:42 UTC
Labels: bug
